### ISSUE TITLE
Is there any chance to get the latest update?

### ISSUE THREAD

**Issue by adsxsunshine** [spicetify/spicetify-cli#1776]
### 📝 Provide a description of the new feature

Spotify has updated 2 times for now. You have ignored the 1st one and that's ok. But for some reason you are still not long for making it after the 2nd update. I get it if the 1st update wasn't big and game-changing but make it now. People love to use the up-to-date software. Why do you need to complicate it, so in order to use Spicetify we need to get the previous and outdated version of Spotify? So my request is that you make the update without any conflicts or debates.

**Comment by kyrie25** [comment]
I understand your frustration as for all others who have reported issues whilst using Spicetify. However, we ask that you understand the following situation:
- We did not *ignore* the 1.1.87 update. It was simply not breaking, nothing significant to patch thus there was no need to publish a release. **Spicetify releases does not always correlate with Spotify updates** and it shouldn't be so, releases are only published as needed.
- As for downgrading Spotify, we simply pointed out the _last known working version_ so that users would get to keep using the customizations that they love. Spotify 1.1.88 was released 3-4 days prior and, again, we did not *ignore* the update, we just simply haven't found a patch yet. The issue regarding the update has already been acknowledged and the workaround has been posted (see #1770).

We do appreciate if you have anything useful, whether it be logs or findings, PRs to contribute and fasten our effort in releasing a patch. Otherwise, we ask for your patience in our effort of maintaining this project ❤️.
