### ISSUE TITLE
[Popup Lyrics] Memory leak

### ISSUE THREAD

**Issue by adufr** [spicetify/spicetify-cli#1925]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.93.896.g3ae3b4f3 (Spotify for macOS (Intel))
- Spicetify version: 2.13.1
```

### 📝 Description

When using the popup lyrics extension's popup for a long time (at least 2 or 3 hours), I noticed that Spotify uses an abnormal amount of RAM.

I haven't been able to pinpoint it more precisely. I will try to provide a screenshot of the process that uses all my RAM as soon I encounter the problem again.

(I haven't tried it yet on my Windows desktop, I'll provide more feedback as soon as I can)

**Comment by adufr** [comment]
Here is the screenshot of the 2 Spotify processes eating my RAM:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/26418696/189893311-e5f1f8ea-078f-4b2d-9217-df297aaefe87.png">

I don't know if this could be a lead, but I do listen to a lot of songs that don't have lyrics (instrumental or just "no lyrics")

**Comment by kyrie25** [comment]
I don't think this is solvable on the CLI/extension side of things, since all the extension does is create a `video` element and request the client to use it as Picture-in-Picture.
Spotify (client) doesn't seem to have any plans or support for videos so it's possible that they have not optimized it for PiP/video usage.

I might be wrong and there may be a Javascript-side patch for it though.

**Comment by iamririxi** [comment]
I don't believe it's memory leak from "popupLyrics" itself. If you will provide us performance logs (from DevTools) when this occurs, we'll look into it, for now I'm closing this issue because there's not a lot of evidence that it's popupLyrics extension.
