### ISSUE TITLE
Unable to start DevTools

### ISSUE THREAD

**Issue by gnuhead-chieb** [spicetify/spicetify-cli#1947]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819(Flatpak)
- Spicetify version: 2.13.1
- System: Kubuntu 22.04.1 X11
```

### 📝 Description

When I run the "spicetify enable-devtools" command, the command completes successfully, but **pressing Ctrl+Shift+I does not start DevTools**.

I already tried adding line "app.enable-developer-mode=true" at ~/.config/spotify/prefs

### 📸 Screenshots

![Screenshot_20220922_053904](https://user-images.githubusercontent.com/41156994/191605892-200b4e10-5bb9-43e2-9a71-32c15f15a734.png)

**Comment by kyrie25** [comment]
Right-click onto the Spicetify client and click on either `Show DevTools` or `Inspect Element` on the dropdown menu.

**Comment by gnuhead-chieb** [comment]
> Right-click onto the Spicetify client and click on either `Show DevTools` or `Inspect Element` on the dropdown menu.

Thanks! it worked.

**Comment by ArjixWasTaken** [comment]
Adding `app.enable-developer-mode=true` to the prefs file doesn't work since spotify removes it on start-up
And `spicetify enable-devtools` doesn't work for some reason, it does complete successfully but there are no devtools

I did try right clicking on the spotify window, unless you meant something else by `spicetify client`, but...i cant right click

The only context menus that appear are the ones for songs/albums/playlists/etc

:information_source: Environment / Computer Info
```markdown
- System: Arch linux x64
- Spotify version: 1.1.84.716.gc5f8b819 (installed thru the AUR)
- Spicetify version: 2.13.1
```

**Comment by kyrie25** [comment]
DevTools is only temporarily enabled after you run the command. Run `spicetify enable-devtools` and right-click on the client right after it launches.

**Comment by ArjixWasTaken** [comment]
That doesn't work, as I said, I tried right clicking...

**Comment by qkrrmsdud1** [comment]
Ctrl + Shift + I, right clicking, and Shift + F10 all don't work for me. Is there another way to get it to work?

**Comment by onewilk** [comment]
how to disable devtools after enable-devtools command ?
