### ISSUE TITLE
Installer breaks Fish config

### ISSUE THREAD

**Issue by foxt** [spicetify/spicetify-cli#2040]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

Spictify installer does not append a `\n` before adding the fish_add_path line. If there is no new line at the end of the config this will break your configuration.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/12257112/205489515-82c93d79-eefa-4d98-a576-25513b4be1d0.png)

![image](https://user-images.githubusercontent.com/12257112/205489526-1542c713-a740-455c-9d6b-7d8c42d72ee5.png)

**Comment by ririxidev** [comment]
Well, 
> Spictify installer does not append a \n before adding the fish_add_path line

because it doesn't need to. We use `>>` with echo which appends anything you provide it to append.
![image](https://user-images.githubusercontent.com/9348108/205497638-75fb5c97-b483-477a-abda-f12d1f9841a1.png)
With that being said, I can't reproduce

**Comment by theRealPadster** [comment]
I think they're actually right. When you use the `>` or `>>` operator, it automatically adds a newline at the end, because that is the standard, valid format. It's incorrect to not have a newline at the end of the file. It doesn't display in terminal, but displays in VS Code. 

<img width="232" alt="image" src="https://user-images.githubusercontent.com/1565883/205505317-32c20516-9a1c-4ade-859c-d3ef346b8037.png">
<img width="153" alt="image" src="https://user-images.githubusercontent.com/1565883/205505327-f905b7b2-fc06-4c18-9d34-a6ec44d54e86.png">

**Comment by foxt** [comment]
@theRealPadster Some shells (such as Fish) do ensure that the prompt always appears on a new line, however, for example, in Bash, if the file does hot have a trailing new line, the shell will appear on the same line. The `>>` operator does not also check for a new line (at least in Fish)

![image](https://user-images.githubusercontent.com/12257112/205505552-ac6d18fd-ca33-4513-91fb-ba9861fcd431.png)
