### ISSUE TITLE
System users share customization

### ISSUE THREAD

**Issue by zkwinkle** [spicetify/spicetify-cli#2112]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify version 1.1.84.716.gc5f8b819, Copyright (c) 2022, Spotify Ltd
- Spicetify version: 2.16.0
- OS: Arch Linux
```

### 📝 Description

I'm having issues trying to use spicetify on more than one user in my Linux system. I'm gonna preface this by saying that I really don't know how spicetify works, but from what I gather it seems like `spicetify` is placing the applied customizations inside `/opt/spotify/Apps`. It also seems to me that it created the `/opt/spotify/Apps` directory when I installed spicetify and it created that directory with the user that installed spicetify (which gets installed system-wide) as the owner.

Making the specific user that installed spicetify the owner of that directory broke spotify for my other users and also of course I couldn't use spicetify with them (if spotify wouldn't even launch, duh). This was easily fixed by changing the permissions in the folder though with the following commands:
```sh
sudo chmod a+wr /opt/spotify
sudo chmod a+wrx /opt/spotify/Apps -R
```

Now both users can launch spotify and apply their preferred spicetify theme. Now, an issue still arises that's been annoying me quite a bit. Each user has a different theme (actually just a different color scheme) in ther spicetify config. But, whenever, for example, user1 runs `spicetify apply` and applies their specific theme, the next time user2 launches spotify it will have user1's theme. user2 can then run `spicetify apply` to fix their client, but likewise, when user1 restarts their spotify client it will now have user2's theme applied. Essentially this means that whenever each user logs in they must apply their spicetify theme and restart spotify.

Would it be possible to apply the themes separately for each system user? Maybe in the process create a different `Apps` folder for each user so that messing with the folders permissions isn't needed?

**Comment by kyrie25** [comment]
The first half of your issue was already mentioned in our FAQ:
https://spicetify.app/docs/advanced-usage/installation#spotify-installed-from-aur

As for the second half:
#### Explaination:
First off, Spicetify stores all customization files, as long as its configuration file `config-xpui` for each users in `$HOME/.config/spicetify`.
When the user runs `apply`, Spicetify injects itself onto `opt/spotify` by copying all the files listed in `config-xpui` as well as inject JavaScript entries onto the client's runtime files. `opt/spotify` is **not** a folder of choice, it is where the Spotify client located its cache and configuration files. For that reason, when you switch users, the content inside the folder stays while Spicetify configuration changes.

### Proposed solution
Since Spicetify doesn't run in the background or has auto-startup (and for many reasons it shouldn't), you can simply edit your Spotify `.desktop` shortcut file to run `spicetify apply` before actually starting the client.
You could also have a script/entry that runs `spicetify apply` on user logon, which is also fairly simple imo.

Hope that helps!

**Comment by zkwinkle** [comment]
Yes indeed I saw it in the FAQ, sorry I was just trying to get in the whole story 😅. But omg I feel a little embarrassed that I didn't think to just run it in my startup file. Thank you for the suggestion! I'm not getting much luck editing the `.desktop` file :/ have never touched with one of these before. But whatever I always run spotify on startup and on that front it's solved. Ty!
