### ISSUE TITLE
[Lyrics Plus] Support multi-line lrc

### ISSUE THREAD

**Issue by aroxu** [spicetify/spicetify-cli#2561]
### 📝 Provide a description of the new feature

Some LRC files contain two or more lines of lyrics in a single timestamp. We would like to see support for this.
The idea is to show all lines with the same timestamp at once.

### ➕ Additional Information

The image below shows the contents of an lrc file:
![image](https://github.com/spicetify/spicetify-cli/assets/30624945/72bc34c1-00e7-4fed-b000-a6f4dcc96e1b)
And the image below is the support for multi-line LRC files in another app ([Musicolet on GooglePlay](https://play.google.com/store/apps/details?id=in.krosbits.musicolet)):
![image](https://github.com/spicetify/spicetify-cli/assets/30624945/b77bd838-cfae-4c44-8ea2-a5258943bcc5)

**Comment by rxri** [comment]
If two or more lines have the same timestamps, it suggests that something is incorrect because the lyrics in your example aren't in the same timestamp as displayed in the screenshot. We have no intentions to add it because it requires creating new way of displaying lyrics, and none of our supported suppliers have this implemented, therefore we will not add it either. I don't believe the 'lrc' format was designed to handle this
