### ISSUE TITLE
Shuffle+ (Error code -1: Resolver not found)

### ISSUE THREAD

**Issue by Wh1rr** [spicetify/spicetify-cli#2590]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.21.1104.g42cf0a50
- Spicetify version: 2.24.2
```

### 📝 Description

Right click a playlist and click 'Play with shuffle+'.

Extra Info:

- Queue does not change
- Error pops up for a few seconds
- Not sure in what update it broke but has previously worked

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/111227035/2357222d-39c0-4284-aa3f-0910d9e5a690)

**Comment by rxri** [comment]
This has been already fixed by https://github.com/spicetify/spicetify-cli/commit/40adf67a6771d2811f17dfd734b68d0b225c4910 & https://github.com/spicetify/spicetify-cli/commit/1ad0eba7bb6b6cfcd77670a167389a90f6d16c48. It seems like the upgrade process didn't update shuffle+ so you need to do it manually

**Comment by Wh1rr** [comment]
Forgot to apply after manually updating the file, sorry!
