### ISSUE TITLE
Help me (error at line 98)

### ISSUE THREAD

**Issue by GreenBlockBuster** [spicetify/spicetify-cli#2591]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
I am on Linux Debian 12
```

### 📝 Description

Help I am unable to install spicetify also I am a beginner

shows this
li/master/install.sh | sh
FETCHING Version 2.24.2
DOWNLOADING https://github.com/spicetify/spicetify-cli/releases/download/v2.24.2/spicetify-2.24.2-linux-amd64.tar.gz
######################################################################## 100.0%
EXTRACTING /home/greenblockbuster/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /home/greenblockbuster/.spicetify/spicetify
REMOVING /home/greenblockbuster/.spicetify/spicetify.tar.gz
sh: 98: [: .bashrc: unexpected operator
spicetify path already set in /home/greenblockbuster/.bashrc, continuing...

spicetify v2.24.2 was installed successfully to /home/greenblockbuster/.spicetify
Run 'spicetify --help' to get started

### 📸 Screenshots

file:///home/greenblockbuster/Pictures/Screenshot_20231007_161412.xcf

**Comment by rxri** [comment]
Your `.bashrc` is corrupted. It's not spicetify related

**Comment by GreenBlockBuster** [comment]
how to fix it?

**Comment by theRealPadster** [comment]
> how to fix it?

1. We don't know workout seeing the contents of the file. 
2. You just posted the file path of a screenshot, and the screenshot itself didn't upload.

**Comment by GreenBlockBuster** [comment]
do you have any idea on how to fix it?

**Comment by theRealPadster** [comment]
> do you have any idea on how to fix it?

No... The command output said there is a syntax error in the file. We don't know what that error is without seeing what is in the file.

**Comment by GreenBlockBuster** [comment]
Do you want to see the file?

**Comment by theRealPadster** [comment]
> Do you want to see the file?

I could take a look if you want

**Comment by KaKi87** [comment]
Hello,

I encountered the same error on Pop OS 22.04, which is also based on Debian 12.

> Your `.bashrc` is corrupted. It's not spicetify related

No it's not corrupted and yes it's Spicetify related, because `source ~/.bashrc` throws no error, and line 98 is even empty.

Turns out, the error is referring to **line 98 of `install.sh`**, which happens to contain the following :

```bash
if [ "$1" == ".zshrc" ] && [ ! -z "${ZDOTDIR}" ]; then
```

Where `$1` is `.bashrc`, the mention of that file name in the error.*

After opening the script in JetBrains IntelliJ running ShellCheck, I noticed the following warning :

![](https://github.com/spicetify/spicetify-cli/assets/21284089/aa744495-910a-408c-b4a4-a389f2bd842f)

> In POSIX sh, == in place of = is undefined. See [SC2039](https://github.com/koalaman/shellcheck/wiki/SC2039).

The linked page indicates the following :

> ### Testing Equality
> `==` operator is not supported in POSIX `sh`
> Bash:
> ```Bash
> if [ "$a" == "$b" ]; then
>     echo "equal"
> fi
> ```
> POSIX:
> ```sh
> if [ "$a" = "$b" ]; then
>     echo "equal"
> fi
> ```

Then I noticed this kind of `bash` vs `sh` warning was present all over the file, indicating that it was written to be a `bash` script and not an `sh` one, which is normal of course.

So, editing that like isn't indeed the proper fix, but changing the shebang from `sh` to `bash` is.

Therefore, I created PR #2774.

I wonder though, how could this have gone unnoticed since the very beginning of the project :shrug:
