### ISSUE TITLE
New Releases stuck on loading

### ISSUE THREAD

**Issue by guiltlab** [spicetify/spicetify-cli#2678]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.25.1011.g0348b2ea
- Spicetify version:
Spicetify v2.27.2
Theme: marketplace
Extensions: hidePodcasts.js, adblock.js, sortByPlayCount.js, star-ratings.js
Custom apps: marketplace, new-releases
```

### 📝 Description

Since I updated spicetify today, the new releases section is stuck on an infinite loading. I have tried restarting spotify, but it didn't change anything. Thanks in advance for the help!

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/45518224/ae426972-e033-4afa-8506-33b4f5bbdc5d)

**Comment by rxri** [comment]
For now you can use `What's new` page made by Spotify which you can enable via Experimental Features 
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/f432c4ab-9be0-47c0-8742-5d164ea514c7). 
I'm not sure if it's worth adapting the same source data from `What's New` since we will display the same results as Spotify because they removed the endpoints that were required for `new releases` to work

**Comment by rxri** [comment]
I've decided to deprecate `New Releases` for Spotify `1.2.25` and higher because it requires unnecessary work and would show the same data as `What's New`. An alternative for `New Releases` is Spotify's `What's New`, which, as previously mentioned, can be enabled through `Experimental Features` if it isn't already enabled

**Comment by guiltlab** [comment]
Appreciate the tip, that's a decent workaround for now ! I understand your point of view if it's a lot of work to fix it.
Would it be possible to get the grid view as before ? It was more practical because it shows many more releases in one screen.
The "dismiss release" feature was super useful as well, I hope this can be integrated in the What's New screen 🙏
