### ISSUE TITLE
xpui.js:1 TypeError: Cannot set properties of undefined (setting 'ReduxStore')

### ISSUE THREAD

**Issue by ItsSintex** [spicetify/spicetify-cli#2805]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.30.1135.g02fef27a
xpui_2024-01-29_1706560054673_02fef27
cef_120.2.3+g7d89c0c+chromium-120.0.6099.199
Runtime: Alloy

- Spicetify version: v2.31.0
```

### 📝 Description

I've been using spicetify for a while, at some point it just didn't seem to work anymore so I gave it some time in case of it just being outdated. Quite a long time has already passed and it still doesn't seem to work.

I already tried both uninstalling spicetify and spotify and nothing seems to have work. When going back to standard spotify there is no issue at all.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/84252548/b15fcded-3bc6-4fc3-8365-4c3e74f44ed7)

**Comment by rxri** [comment]
This issue appears when latest wrapper is not applied basically (missing this specific line: https://github.com/spicetify/spicetify-cli/blob/master/jsHelper/spicetifyWrapper.js#L303). What I recommend doing is, uninstall spotify (clean every leftover), install it again, and to be entirely sure uninstall spicetify as well (with cleaning every leftover like with spotify) and installing it again. This issue was brought to us before and from our testing we can't reproduce it because it's from outdated applied wrapper

**Comment by rxri** [comment]
Great to hear you resolved this issue. Enjoy using our new update 😉
