### ISSUE TITLE
Add program to winget package manager

### ISSUE THREAD

**Issue by LBlend** [spicetify/spicetify-cli#708]
Since you already support 3rd party package managers like Scoop and Chocolatey you should add it to the winget repo as well.

https://github.com/microsoft/winget-pkgs

**Comment by Tread-2036** [comment]
I think as of yet, since there isn't (there doesn't seem to be) any zip support, this will have to wait, until either Spicetify either uses a .exe silent installer (perhaps like a self extracting archive) or winget allows unzipping as installing an app.

wingetcreate certainly doesn't support it yet and there is an ongoing issue regarding this on the winget-cli repo: https://github.com/microsoft/winget-cli/issues/140
![image](https://user-images.githubusercontent.com/68092214/120576586-60857780-c466-11eb-89cc-d74ad145517b.png)

**Comment by CryoRenegade** [comment]
we could make a tiny exe that runs the ps1 line, but the problem from there is that spiceify can update itself from the cli, and winget installs stuff to either appdata or program files,  so I see no reason to use winget to install this due to the fact that the ps1 installs it wherever you want with no hastle.

**Comment by Tread-2036** [comment]
@CryoRenegade You make a fair point but using winget would to install Spicetify using simply `winget install spicetify` over the full command from the README. I know I am lazy, but say for example when changing computers or installing on multiple, using just winget could be a little more streamlined.

**Comment by CryoRenegade** [comment]
Fair... But Ctrl+C, Ctrl+V seems easier than `winget install spicetifyi-cli` plus the extra editions for the community themes that need to be downloaded

**Comment by LBlend** [comment]
You could say the same thing about it being available choco and scoop though. You could just copy-paste the powershell script url and go on about your day. The benefit though is that you would only need one package manager that can update all the programs on your computer in batch, including spicetify. There won't be need to have multiple package managers or manually updating spicetify.

But yeah I see your point and if it's an hassle to make it compatible then there's no need to do it.

**Comment by Ixyk-Wolf** [comment]
One other idea, I don't know if this is possible in Go though, is to have a string with the binary copy of the spicetify zip and have the .exe install it from there.

**Comment by saxobroko** [comment]
https://adamtheautomator.com/ps1-to-exe/

The first one, ps2exe. Seems like it can do the trick. When releasing spicetify versions they just need to run a simple command.

**Comment by CryoRenegade** [comment]
That would be the best option if khanas were to add this tool to winget

**Comment by sitiom** [comment]
Winget 1.4 has just been released, supporting zip installations. I have already created a PR for Spicetify to winget-pkgs:

- https://github.com/microsoft/winget-pkgs/pull/94750

Afterwards, the [Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) workflow would have to be set up in this repo for automatic package updates.

**Comment by rxri** [comment]
Seems like spicetify is in winget now! Thanks @sitiom. We'll add CI to update it automatically very soon
![image](https://user-images.githubusercontent.com/9348108/216667340-1f17d962-5d2a-482a-aadc-4571c75fcc07.png)

**Comment by sitiom** [comment]
https://github.com/vedantmgoyal2009/winget-releaser/issues/82 would have to be resolved first for Winget Releaser.
